#!/bin/bash

tags=$(curl -sS "https://api.github.com/repos/GoogleChrome/puppeteer/releases" | jq -r "reverse|.[].tag_name")

for tag in $tags
do
    chromium_revision=$(curl -sS "https://raw.githubusercontent.com/GoogleChrome/puppeteer/$tag/package.json" | jq -r ".puppeteer.chromium_revision")
    docker build --build-arg CHROMIUM_REVISION=$chromium_revision -t chromie/headless-chrome-puppeteer:$tag .
    docker push chromie/headless-chrome-puppeteer:$tag
    docker rmi chromie/headless-chrome-puppeteer:$tag
done
